*** Variables ***
${globalSchemaLogin}                ${CURDIR}/../schemas/login.json
${globalSchemaLoginError}           ${CURDIR}/../schemas/loginError.json
${globalSchemaUsersWithId}          ${CURDIR}/../schemas/usersWithId.json
${globalSchemaUsers}                ${CURDIR}/../schemas/users.json
${globalSchemaUsersPost}            ${CURDIR}/../schemas/usersPost.json
${globalSchemaUsersPostError}       ${CURDIR}/../schemas/usersPostError.json
${globalSchemaUsersDelete}          ${CURDIR}/../schemas/usersDelete.json
